# Generated by Django 3.2.9 on 2021-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
