# Generated by Django 3.2.9 on 2021-11-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211106_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notebook',
            name='price',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
