# Generated by Django 3.2.9 on 2021-11-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211107_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Monitores',
        ),
    ]
