# Generated by Django 3.2.9 on 2021-11-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tipoproducto',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
