# Generated by Django 3.2.9 on 2021-11-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_products_tipoproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitores',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Procesadores',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
